version: 2

jobs:
  macos:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test
      - run:
          name: Compile code with optimizations
          command: swift build -c release


  linux-vapor:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - run:
          name: Clone Vapor
          command: git clone -b master https://github.com/vapor/vapor.git
          working_directory: ~/
      - run:
          name: Switch Vapor to this WebSocket revision
          command: swift package edit WebSocket --revision $CIRCLE_SHA1
          working_directory: ~/vapor
      - run:
          name: Run Vapor unit tests
          command: swift test
          working_directory: ~/vapor


workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-vapor
      # - macos

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
      # - macos
