name: test
on:
- pull_request
jobs:
  websocket-kit_xenial:
    container: 
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  websocket-kit_bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  vapor:
    container: 
      image: vapor/swift:5.2
    runs-on: ubuntu-latest
    steps:
    - run: git clone -b master https://github.com/vapor/vapor.git
      working-directory: ./
    - run: swift package edit websocket-kit --revision ${{ github.sha }}
      working-directory: ./vapor
    - run: swift test --enable-test-discovery --sanitize=thread
      working-directory: ./vapor
